const SEV_STYLE = {
  Critical: {
    badge: "bg-red-100 text-[#dc2626]",
    bar: "bg-[#dc2626]",
    ring: "border-l-[#dc2626]",
  },
  Warning: {
    badge: "bg-amber-100 text-[#b45309]",
    bar: "bg-amber-500",
    ring: "border-l-[#b45309]",
  },
  Info: {
    badge: "bg-blue-100 text-[#2563eb]",
    bar: "bg-[#2563eb]",
    ring: "border-l-[#2563eb]",
  },
};

function Section({ icon, title, children }) {
  return (
    <div className="space-y-2">
      <div className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-widest text-slate-400">
        <span className="material-symbols-outlined text-[15px] text-navy">{icon}</span>
        {title}
      </div>
      {children}
    </div>
  );
}

function Kv({ k, v, mono = false }) {
  return (
    <div className="flex items-start justify-between gap-3 py-1.5 border-b border-slate-50 last:border-0">
      <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wide shrink-0 pt-0.5">
        {k}
      </span>
      <span
        className={`text-xs font-semibold text-slate-800 text-right break-words ${mono ? "font-mono" : ""}`}
      >
        {v}
      </span>
    </div>
  );
}

function buildReport(e, status) {
  const L = [];
  L.push("TRINETRA · ALERT CASE FILE");
  L.push("=".repeat(46));
  L.push(`Alert ID   : ${e.id}`);
  L.push(`Raised     : ${e.dateLabel} · ${e.timeLabel} IST`);
  L.push(`Severity   : ${e.severity}`);
  L.push(`Category   : ${e.categoryLabel}`);
  L.push(`Status     : ${status.toUpperCase()}`);
  L.push(`Source     : ${e.live ? "LIVE GRID (backend ledger)" : "PREVIEW (simulated feed)"}`);
  L.push("");
  L.push(`WHY THIS ALERT`);
  L.push(e.why);
  L.push("");
  L.push(`CAUSE`);
  L.push(e.cause);
  L.push("");
  L.push(`TRIGGER & MEASURE`);
  L.push(`Rule       : ${e.rule}`);
  L.push(`Limit      : ${e.measure.limit}`);
  L.push(`Observed   : ${e.measure.observed}`);
  L.push(`Outcome    : ${e.outcome}`);
  L.push(`Confidence : ${e.confidence}%`);
  L.push("");
  L.push(`VEHICLE`);
  L.push(`Plate      : ${e.vehicle.plate}`);
  L.push(`Class      : ${e.vehicle.class}`);
  L.push(`Make       : ${e.vehicle.make} · ${e.vehicle.color}`);
  L.push(`State      : ${e.vehicle.state} · ${e.vehicle.owner}`);
  L.push("");
  L.push(`LOCATION`);
  L.push(`Camera     : ${e.cam}`);
  L.push(`Road       : ${e.road}`);
  L.push(`Zone       : ${e.zone} · ${e.dir} · heading ${e.heading}`);
  L.push("");
  L.push(`TRAJECTORY : ${e.trajectory.join(" → ")}`);
  L.push("");
  L.push(`ADDITIONAL DETAILS`);
  for (const r of e.additional) L.push(`- ${r.k}: ${r.v}`);
  L.push("");
  L.push(`Generated by TRINETRA National Control Room · ${new Date().toLocaleString("en-IN")}`);
  return L.join("\n");
}

/**
 * AlertDetailPanel — right-hand case file for the selected alert.
 * Why it fired, what triggered it, measured evidence + confidence,
 * vehicle / location / trajectory / extras, print + download,
 * and resolve / delete actions (parents own the confirm flow).
 */
export default function AlertDetailPanel({
  alert,
  status = "open",
  onResolve = () => {},
  onDelete = () => {},
  onTrace = () => {},
  notify = () => {},
}) {
  if (!alert) {
    return (
      <div className="rounded-2xl border border-dashed border-slate-300 bg-white/60 p-10 text-center h-full flex flex-col items-center justify-center">
        <span className="material-symbols-outlined text-[44px] text-slate-300">fact_check</span>
        <p className="mt-3 font-display font-extrabold text-navy">No Alert Selected</p>
        <p className="text-sm text-slate-500 max-w-xs mx-auto mt-1">
          Click any alert headline on the left to open its full case file here —
          cause, evidence, confidence and actions.
        </p>
      </div>
    );
  }

  const sev = SEV_STYLE[alert.severity] || SEV_STYLE.Info;

  const doPrint = () => window.print();

  const doDownload = () => {
    const blob = new Blob([buildReport(alert, status)], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `trinetra-alert-${String(alert.id).slice(0, 8)}.txt`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 800);
    notify("Case file downloaded");
  };

  return (
    <div
      className={`alerts-print-area rounded-2xl bg-white border border-slate-100 shadow-panel overflow-hidden border-l-4 ${sev.ring}`}
    >
      {/* header */}
      <div className="px-5 pt-4 pb-3 border-b border-slate-100 bg-gradient-to-r from-navy/[0.04] to-transparent">
        <div className="flex flex-wrap items-center gap-2">
          <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase ${sev.badge}`}>
            {alert.severity}
          </span>
          <span className="px-2 py-0.5 rounded-full text-[10px] font-bold uppercase bg-navy/5 text-navy inline-flex items-center gap-1">
            <span className="material-symbols-outlined text-[13px]">{alert.categoryIcon}</span>
            {alert.categoryLabel}
          </span>
          <span
            className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase ${
              alert.live ? "bg-signal/10 text-signal-dark" : "bg-amber-50 text-amber-600"
            }`}
          >
            {alert.live ? "Live grid" : "Preview"}
          </span>
          {status === "resolved" && (
            <span className="px-2 py-0.5 rounded-full text-[10px] font-bold uppercase bg-emerald-100 text-emerald-700 inline-flex items-center gap-1">
              <span className="material-symbols-outlined text-[13px]">task_alt</span>
              Resolved
            </span>
          )}
          <span className="ml-auto text-[11px] text-slate-400 font-semibold">
            {alert.dateLabel} · {alert.timeLabel} IST
          </span>
        </div>
        <h2 className="mt-2 font-display text-lg font-extrabold text-slate-900 leading-snug">
          {alert.description}
        </h2>
        <p className="text-xs text-slate-500 font-mono mt-0.5">#{String(alert.id).slice(0, 13)}</p>
      </div>

      <div className="px-5 py-4 space-y-5 max-h-[calc(100vh-320px)] min-h-[300px] overflow-y-auto">
        {/* why */}
        <div className="rounded-xl bg-navy/[0.04] border border-navy/10 p-3.5">
          <Section icon="help" title="Why was this alert raised?">
            <p className="text-sm font-bold text-navy leading-snug">{alert.why}</p>
            <p className="text-[13px] text-slate-600 leading-relaxed mt-1">{alert.cause}</p>
          </Section>
        </div>

        {/* trigger + confidence */}
        <Section icon="science" title="Trigger & measured evidence">
          <div className="rounded-xl border border-slate-200 p-3.5 space-y-3">
            <p className="text-xs font-bold text-slate-800">{alert.rule}</p>
            <div className="grid grid-cols-2 gap-2">
              <div className="rounded-lg bg-slate-50 px-3 py-2">
                <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Limit / expected</p>
                <p className="text-sm font-extrabold text-slate-700 mt-0.5">{alert.measure.limit}</p>
              </div>
              <div className="rounded-lg bg-red-50/60 border border-red-100 px-3 py-2">
                <p className="text-[10px] font-bold uppercase tracking-wider text-red-400">Observed</p>
                <p className="text-sm font-extrabold text-red-700 mt-0.5">{alert.measure.observed}</p>
              </div>
            </div>
            <div>
              <div className="flex items-center justify-between text-[11px] font-bold">
                <span className="uppercase tracking-wider text-slate-400">Detection confidence</span>
                <span className="text-navy">{alert.confidence}%</span>
              </div>
              <div className="mt-1.5 h-2 rounded-full bg-slate-100 overflow-hidden">
                <div
                  className={`h-full rounded-full ${sev.bar}`}
                  style={{ width: `${alert.confidence}%` }}
                />
              </div>
              <p className="text-[11px] text-slate-500 mt-1.5">
                Fused OCR confidence, registry match and corridor plausibility. Above 75% auto-escalates.
              </p>
            </div>
            <p className="text-xs font-semibold text-signal-dark bg-signal/10 rounded-lg px-3 py-2 inline-flex items-center gap-1.5">
              <span className="material-symbols-outlined text-[15px]">verified</span>
              {alert.outcome}
            </p>
          </div>
        </Section>

        {/* vehicle */}
        <Section icon="directions_car" title="Vehicle details">
          <div className="rounded-xl border border-slate-200 p-3.5">
            <span className="inline-block px-3 py-1 rounded bg-white font-display font-extrabold tracking-wider text-slate-900 shadow-sm border border-slate-200">
              {alert.vehicle.plate}
            </span>
            <div className="mt-2">
              <Kv k="Class" v={alert.vehicle.class} />
              <Kv k="Make / colour" v={`${alert.vehicle.make} · ${alert.vehicle.color}`} />
              <Kv k="Registration" v={`${alert.vehicle.state} · ${alert.vehicle.owner}`} />
              {alert.speed && <Kv k="Speed" v={alert.speed} mono />}
            </div>
          </div>
        </Section>

        {/* location */}
        <Section icon="videocam" title="Location">
          <div className="rounded-xl border border-slate-200 p-3.5">
            <Kv k="Camera" v={alert.cam} mono />
            <Kv k="Road" v={alert.road} />
            <Kv k="Zone" v={`${alert.zone} · ${alert.dir}`} />
            <Kv k="Heading" v={alert.heading} mono />
          </div>
        </Section>

        {/* trajectory */}
        <Section icon="route" title="Trajectory">
          <div className="rounded-xl border border-slate-200 p-3.5">
            <div className="flex flex-wrap items-center gap-1.5">
              {alert.trajectory.map((c, i) => (
                <span key={`${c}-${i}`} className="inline-flex items-center gap-1.5">
                  <span className="px-2 py-1 rounded-lg bg-navy/5 text-navy text-[11px] font-bold font-mono">
                    {c}
                  </span>
                  {i < alert.trajectory.length - 1 && (
                    <span className="material-symbols-outlined text-[14px] text-slate-300">arrow_forward</span>
                  )}
                </span>
              ))}
            </div>
            <button
              onClick={() => onTrace(alert.vehicle.plate)}
              className="mt-3 w-full px-3 py-2 rounded-lg text-xs font-bold bg-navy text-white hover:bg-navy-dark transition-colors inline-flex items-center justify-center gap-1.5 alerts-no-print"
            >
              <span className="material-symbols-outlined text-[16px]">travel_explore</span>
              Trace full journey in Trajectory Search
            </button>
          </div>
        </Section>

        {/* additional */}
        <Section icon="info" title="Additional details">
          <div className="rounded-xl border border-slate-200 px-3.5 py-1.5">
            {alert.additional.map((r, i) => (
              <Kv key={i} k={r.k} v={r.v} mono={/CAM_|FIR|ID|Ticket|Dossier/i.test(String(r.v))} />
            ))}
          </div>
        </Section>
      </div>

      {/* actions */}
      <div className="alerts-no-print px-5 py-3.5 border-t border-slate-100 bg-slate-50/60 flex flex-wrap items-center gap-2">
        <button
          onClick={doPrint}
          className="px-3 py-2 rounded-lg text-xs font-bold bg-white border border-slate-200 text-slate-700 hover:bg-slate-100 transition-colors inline-flex items-center gap-1.5"
        >
          <span className="material-symbols-outlined text-[16px]">print</span>
          Print
        </button>
        <button
          onClick={doDownload}
          className="px-3 py-2 rounded-lg text-xs font-bold bg-white border border-slate-200 text-slate-700 hover:bg-slate-100 transition-colors inline-flex items-center gap-1.5"
        >
          <span className="material-symbols-outlined text-[16px]">download</span>
          Download
        </button>
        <span className="flex-1" />
        {status !== "resolved" ? (
          <button
            onClick={onResolve}
            className="px-3 py-2 rounded-lg text-xs font-bold bg-signal/10 text-signal-dark hover:bg-signal/20 transition-colors inline-flex items-center gap-1.5"
          >
            <span className="material-symbols-outlined text-[16px]">task_alt</span>
            Resolve
          </button>
        ) : (
          <span className="px-3 py-2 rounded-lg text-xs font-bold bg-emerald-100 text-emerald-700 inline-flex items-center gap-1.5">
            <span className="material-symbols-outlined text-[16px]">check_circle</span>
            Resolved
          </span>
        )}
        <button
          onClick={onDelete}
          className="px-3 py-2 rounded-lg text-xs font-bold bg-[#dc2626] hover:bg-[#b91c1c] text-white transition-colors inline-flex items-center gap-1.5"
        >
          <span className="material-symbols-outlined text-[16px]">delete</span>
          Delete
        </button>
      </div>
    </div>
  );
}
